"""Add Transaction Table 2

Revision ID: 557d3e4128a2
Revises: ed3614478e2b
Create Date: 2023-04-20 10:19:32.821731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557d3e4128a2'
down_revision = 'ed3614478e2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('total_ether_sent', sa.FLOAT(), nullable=True),
    sa.Column('avg_min_between_received_tnx', sa.FLOAT(), nullable=True),
    sa.Column('time_diff', sa.FLOAT(), nullable=True),
    sa.Column('sent_tnx', sa.Integer(), nullable=True),
    sa.Column('unique_received_from_addresses', sa.Integer(), nullable=True),
    sa.Column('number_of_created_contracts', sa.Integer(), nullable=True),
    sa.Column('received_tnx', sa.Integer(), nullable=True),
    sa.Column('unique_sent_to_addresses', sa.Integer(), nullable=True),
    sa.Column('min_value_received', sa.FLOAT(), nullable=True),
    sa.Column('max_value_received', sa.FLOAT(), nullable=True),
    sa.Column('avg_val_received', sa.FLOAT(), nullable=True),
    sa.Column('min_val_sent', sa.FLOAT(), nullable=True),
    sa.Column('avg_val_sent', sa.FLOAT(), nullable=True),
    sa.Column('erc20_total_ether_received', sa.FLOAT(), nullable=True),
    sa.Column('min_value_sent_to_contract', sa.FLOAT(), nullable=True),
    sa.Column('max_val_sent_to_contract', sa.FLOAT(), nullable=True),
    sa.Column('avg_value_sent_to_contract', sa.FLOAT(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('avg_min_between_sent_tnx', sa.FLOAT(), nullable=True),
    sa.Column('total_ether_received', sa.FLOAT(), nullable=True),
    sa.Column('total_ether_sent_contracts', sa.FLOAT(), nullable=True),
    sa.Column('total_ether_balance', sa.FLOAT(), nullable=True),
    sa.Column('total_erc20_tnxs', sa.FLOAT(), nullable=True),
    sa.Column('max_val_sent', sa.FLOAT(), nullable=True),
    sa.Column('erc20_total_ether_sent', sa.FLOAT(), nullable=True),
    sa.Column('erc20_total_ether_sent_contract', sa.FLOAT(), nullable=True),
    sa.Column('erc20_uniq_sent_addr', sa.FLOAT(), nullable=True),
    sa.Column('erc20_uniq_rec_contract_addr', sa.FLOAT(), nullable=True),
    sa.Column('erc20_uniq_sent_addr_new', sa.FLOAT(), nullable=True),
    sa.Column('erc20_uniq_rec_addr', sa.FLOAT(), nullable=True),
    sa.Column('erc20_avg_time_between_sent_tnx', sa.FLOAT(), nullable=True),
    sa.Column('erc20_avg_time_between_rec_tnx', sa.FLOAT(), nullable=True),
    sa.Column('erc20_avg_time_between_rec_2_tnx', sa.FLOAT(), nullable=True),
    sa.Column('erc20_avg_time_between_contract_tnx', sa.FLOAT(), nullable=True),
    sa.Column('erc20_min_val_rec', sa.FLOAT(), nullable=True),
    sa.Column('erc20_max_val_rec', sa.FLOAT(), nullable=True),
    sa.Column('erc20_avg_val_rec', sa.FLOAT(), nullable=True),
    sa.Column('erc20_min_val_sent', sa.FLOAT(), nullable=True),
    sa.Column('erc20_max_val_sent', sa.FLOAT(), nullable=True),
    sa.Column('erc20_avg_val_sent', sa.FLOAT(), nullable=True),
    sa.Column('erc20_min_val_sent_contract', sa.FLOAT(), nullable=True),
    sa.Column('erc20_max_val_sent_contract', sa.FLOAT(), nullable=True),
    sa.Column('erc20_avg_val_sent_contract', sa.FLOAT(), nullable=True),
    sa.Column('erc20_uniq_sent_token_name', sa.FLOAT(), nullable=True),
    sa.Column('erc20_uniq_rec_token_name', sa.FLOAT(), nullable=True),
    sa.Column('erc20_most_sent_token_type', sa.String(), nullable=True),
    sa.Column('erc20_most_rec_token_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
