"""Added model status table

Revision ID: 67b6fae7dfc3
Revises: 557d3e4128a2
Create Date: 2023-04-20 12:47:41.456754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b6fae7dfc3'
down_revision = '557d3e4128a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensitivity', sa.FLOAT(), nullable=True),
    sa.Column('specificity', sa.FLOAT(), nullable=True),
    sa.Column('precision', sa.FLOAT(), nullable=True),
    sa.Column('recall', sa.FLOAT(), nullable=True),
    sa.Column('f1', sa.FLOAT(), nullable=True),
    sa.Column('manual_retraining_necessity', sa.String(), nullable=True),
    sa.Column('tuned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_status')
    # ### end Alembic commands ###
