"""Add Transaction Table 2

Revision ID: ed3614478e2b
Revises: af3fee93eb02
Create Date: 2023-04-20 10:02:08.306713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3614478e2b'
down_revision = 'af3fee93eb02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
