from sqlalchemy import Column, Integer, String, FLOAT
from database import Base
from sqlalchemy.sql.sqltypes import TIMESTAMP
from sqlalchemy.sql.expression import text

class Post(Base):
    __tablename__ = "transactions"
    id = Column(Integer,primary_key=True,nullable=False)
    address = Column(String,nullable=False)
    flag = Column(Integer) 
    total_ether_sent= Column(FLOAT)
    avg_min_between_received_tnx= Column(FLOAT)
    time_diff= Column(FLOAT)
    sent_tnx= Column(Integer)
    unique_received_from_addresses= Column(Integer)
    number_of_created_contracts= Column(Integer)
    received_tnx= Column(Integer)
    unique_sent_to_addresses= Column(Integer)
    min_value_received= Column(FLOAT)
    max_value_received= Column(FLOAT)
    avg_val_received= Column(FLOAT)
    min_val_sent= Column(FLOAT)
    avg_val_sent= Column(FLOAT)
    erc20_total_ether_received= Column(FLOAT)
    min_value_sent_to_contract= Column(FLOAT)
    max_val_sent_to_contract= Column(FLOAT)
    avg_value_sent_to_contract= Column(FLOAT)
    total_transactions= Column(Integer)
    avg_min_between_sent_tnx= Column(FLOAT)
    total_ether_received= Column(FLOAT)
    total_ether_sent_contracts= Column(FLOAT)
    total_ether_balance= Column(FLOAT)
    total_erc20_tnxs= Column(FLOAT)
    max_val_sent= Column(FLOAT)
    erc20_total_ether_sent= Column(FLOAT)
    erc20_total_ether_sent_contract= Column(FLOAT)
    erc20_uniq_sent_addr= Column(FLOAT)
    erc20_uniq_rec_contract_addr= Column(FLOAT)
    erc20_uniq_sent_addr_new= Column(FLOAT)
    erc20_uniq_rec_addr= Column(FLOAT)
    erc20_avg_time_between_sent_tnx= Column(FLOAT)
    erc20_avg_time_between_rec_tnx= Column(FLOAT)
    erc20_avg_time_between_rec_2_tnx= Column(FLOAT)
    erc20_avg_time_between_contract_tnx= Column(FLOAT)
    erc20_min_val_rec= Column(FLOAT)
    erc20_max_val_rec= Column(FLOAT)
    erc20_avg_val_rec= Column(FLOAT)
    erc20_min_val_sent= Column(FLOAT)
    erc20_max_val_sent= Column(FLOAT)
    erc20_avg_val_sent= Column(FLOAT)
    erc20_min_val_sent_contract= Column(FLOAT)
    erc20_max_val_sent_contract= Column(FLOAT)
    erc20_avg_val_sent_contract= Column(FLOAT)
    erc20_uniq_sent_token_name= Column(FLOAT)
    erc20_uniq_rec_token_name= Column(FLOAT)
    erc20_most_sent_token_type= Column(String)
    erc20_most_rec_token_type= Column(String)

class Model_Status(Base):
    __tablename__ = "model_status"
    id = Column(Integer,primary_key=True,nullable=False)
    sensitivity= Column(FLOAT)
    specificity= Column(FLOAT)
    precision= Column(FLOAT)
    recall= Column(FLOAT)
    f1= Column(FLOAT)
    manual_retraining_necessity= Column(String)
    tuned_at = Column(TIMESTAMP(timezone=True),nullable=False,server_default=text('now()'))

